# Generated by Django 5.0.6 on 2024-06-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=200)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('level', models.CharField(blank=True, choices=[('Hard', 'Hard'), ('Easy', 'Easy'), ('Medium', 'Medium')], max_length=10)),
            ],
        ),
    ]
