# Generated by Django 5.0.6 on 2024-06-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_solution_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.CharField(default='No constraints', max_length=200),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.CharField(default='General', max_length=300),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.CharField(default='General', max_length=300),
        ),
    ]
