# Generated by Django 5.0.6 on 2024-06-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_constraints_problem_input_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, default='No constraints'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_format',
            field=models.TextField(blank=True, default='General'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_format',
            field=models.TextField(blank=True, default='General'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='verdict',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(blank=True, default=None),
        ),
    ]
