# Generated by Django 5.0.6 on 2024-06-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_constraints_alter_problem_input_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(blank=True, default=None),
        ),
    ]
