# Generated by Django 5.0.6 on 2024-06-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_testcase_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='verdict',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
