# Generated by Django 5.0.6 on 2024-06-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_solution_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='num_correct_testcases',
            field=models.IntegerField(default=0),
        ),
    ]
