# Generated by Django 5.0.6 on 2024-06-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_solution_num_correct_testcases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='num_correct_testcases',
        ),
    ]
