# Generated by Django 5.0.6 on 2024-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_remove_solution_num_correct_testcases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.TextField(blank=True, default='General'),
        ),
    ]
