# Generated by Django 5.0.6 on 2024-07-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_alter_problem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(blank=True, default='General'),
        ),
    ]
