# Generated by Django 5.0.6 on 2024-06-24 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_constraints_problem_input_format_and_more'),
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
    ]
