# Generated by Django 5.0.6 on 2024-06-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0004_alter_codesubmission_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('c', 'C'), ('cpp', 'C++')], max_length=100),
        ),
    ]
