# Generated by Django 5.0.6 on 2024-06-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_alter_codesubmission_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesubmission',
            name='problem',
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
