# Generated by Django 5.0.6 on 2024-06-30 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_solution_verdict'),
        ('submit', '0006_remove_codesubmission_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('c', 'C'), ('cpp', 'C++')], max_length=100),
        ),
    ]
